import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MdButtonModule, 
  MdCheckboxModule, 
  MdIconModule, 
  MdInputModule, 
  MdProgressSpinnerModule, 
  MdToolbarModule, 
  MdMenuModule,
  MdSidenavModule,
  MdCardModule,
  MdListModule,
  MdSelectModule,
  MdTabsModule } from '@angular/material';

@NgModule({
  imports: [CommonModule, 
    MdButtonModule, 
    MdCheckboxModule, 
    MdIconModule, 
    MdInputModule, 
    MdProgressSpinnerModule, 
    MdToolbarModule, 
    MdMenuModule,
    MdSidenavModule,
    MdCardModule,
    MdListModule,
    MdSelectModule,
    MdTabsModule],
  exports: [CommonModule, 
    MdButtonModule, 
    MdCheckboxModule, 
    MdIconModule, 
    MdInputModule, 
    MdProgressSpinnerModule, 
    MdToolbarModule, 
    MdMenuModule,
    MdSidenavModule,
    MdCardModule,
    MdListModule,
    MdSelectModule,
    MdTabsModule],
})
export class MaterialModule { }